language: node

services: docker

node_js:
  - 12

cache:
  directories:
    - node_modules

before_script:
  - touch .env
  - echo DB=$DB >> .env
  - echo T_DB=$T_DB >> .env
  - echo PORT=$PORT >> .env
  - echo NODE_ENV=$NODE_ENV >> .env
  - echo JWT_SECRET=$JWT_SECRET >> .env
  - echo JWT_EXPIRE=$JWT_EXPIRE >> .env
  - echo REF_SECRET=$REF_SECRET >> .env
  - echo REF_EXPIRE=$REF_EXPIRE >> .env
  - echo MG_DOMAIN=$MG_DOMAIN >> .env
  - echo MG_KEY=$MG_KEY >> .env
  - echo CODECOV_TOKEN=$CODECOV_TOKEN >> .env
  - chmod +x ./scripts/deploy.sh
  - chmod +x ./scripts/deploy.staging.sh

script:
  - docker-compose -f docker-compose.ci.yml up --abort-on-container-exit

after_script:
  - docker-compose -f docker-compose.ci.yml down

deploy:
  - provider: script
    script: './scripts/deploy.sh'
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: './scripts/deploy.staging.sh'
    skip_cleanup: true
    on:
      branch: staging

branches:
  only:
    - master
    - staging

notifications:
  email: false
