language: node

services: docker

node_js:
  - 12

before_script:
  - touch .env
  - echo DB=$DB >> .env
  - echo T_DB=$T_DB >> .env
  - echo PORT=$PORT >> .env
  - echo NODE_ENV=$NODE_ENV >> .env
  - echo JWT_SECRET=$JWT_SECRET >> .env
  - echo JWT_EXPIRE=$JWT_EXPIRE >> .env
  - echo REF_SECRET=$REF_SECRET >> .env
  - echo REF_EXPIRE=$REF_EXPIRE >> .env
  - echo MG_DOMAIN=$MG_DOMAIN >> .env
  - echo MG_KEY=$MG_KEY >> .env
  - echo COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN >> .env
  - chmod +x health_check.sh

script:
  - docker-compose -f docker-compose.ci.yml up && docker-compose -f docker-compose.ci.yml down
