version: '3'
services:
  dev_api:
    container_name: dev_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    container_name: db
    env_file:
      - .env
    image: postgres
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - '5432:5432'
