version: '3'

services:
  staging_api:
    container_name: staging_api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        build: staging
    restart: always
    environment:
      VIRTUAL_HOST: staging.getspotter.io
      LETSENCRYPT_HOST: staging.getspotter.io
      LETSENCRYPT_EMAIL: team@getspotter.io
      VIRTUAL_PORT: 5000
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - db

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs/etc/nginx/certs

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs

  db:
    container_name: db
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - database:/data/db

volumes:
  database:
    external: true
  vhost:
  html:
  certs:
