version: '3'
services:
  staging_api:
    container_name: staging_api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        build: staging
    restart: always
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    container_name: db
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - database:/data/db
volumes:
  database:
    external: true
