version: '3'
services:
  api:
    container_name: api
    restart: always
    env_file:
      - .env
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    container_name: db
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - database:/data/db
volumes:
  database:
    external: true
