version: '3'
services:
  dev_api:
    container_name: dev_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    restart: always
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    container_name: db
    logging:
      driver: none
    image: mongo
    ports:
      - '27017:27017'
